name: Test

on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3

      - name: Go Tests
        run: go test ./...